// This file is auto-generated by deploy-infra.ps1
// It will be overwritten with the real API Gateway URL after deployment.
// Do not edit manually.
window.USER_TRACKER_API = "https://517p6ffpyi.execute-api.eu-west-1.amazonaws.com/prod";
