// This file is auto-generated by deploy-infra.ps1
// It will be overwritten with the real API Gateway URL after deployment.
// Do not edit manually.
window.USER_TRACKER_API = "REPLACE_WITH_API_URL";
